version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "logicful"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19p40fjkfi81k"
s3_prefix = "logicful"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

