AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  logicful

  Sample SAM Template for logicful

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 15
    Environment:
      Variables:
        ENV: !Ref Stage
        S3_ENDPOINT: s3.wasabisys.com
        S3_KEY: BO7Z2Y1MUUL07XN14RRO
        S3_SECRET: HmSMKlkeGKJzsOaVLjTsA7LQIMm1uU60GXeMYW1G
        DYNAMO_REGION: us-east-1
        DYNAMO_IS_LOCAL: false
        DYNAMO_ENDPOINT: FILLED_IN_BY_AWS
        OPTION_SETS_TABLE: !Ref OptionSetsTable
        SUBMISSION_QUEUE_LOCKS_TABLE: !Ref SubmissionsQueueLocksTable
        CONTENT_BLOCKS_TABLE: !Ref ContentBlocksTable
        DATA_TABLE: !Ref DataTable
        JWT_SIGN_TOKEN : XRQ9m99CnEDDU33MOsafGTOXbPbgAm
        GOOGLE_OAUTH_SECRET: bzxPS_Ct4UDWyFwcuiuEhnRY


Resources:

  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: Folder
          AttributeType: S
        - AttributeName: FormId
          AttributeType: S
        - AttributeName: SubmissionFormId
          AttributeType: S
        - AttributeName: CreationDate
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: FormFolderIndex
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          KeySchema:
            - AttributeName: Folder
              KeyType: HASH
            - AttributeName: FormId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: SubmissionsByDate
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          KeySchema:
            - AttributeName: SubmissionFormId
              KeyType: HASH
            - AttributeName: CreationDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UnprocessedSubmissionsIndex
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          KeySchema:
            - AttributeName: SubmissionFormId
              KeyType: HASH
            - AttributeName: NewSubmissionKey
              KeyType: RANGE
          Projection:
              ProjectionType: ALL
        - IndexName: UserByEmail
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  OptionSetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SubmissionsQueueLocksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ContentBlocksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  StagingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  Api:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: lambda/main
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY
            RestApiId: !Ref StagingApi

  ProcessSubmissionsJob:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: lambda/cron/process_submissions
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(1 minutes)


Outputs:
  StagingApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${StagingApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/api/"
