AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  logicful

  Sample SAM Template for logicful

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 15
    Environment:
      Variables:
        S3_ENDPOINT: s3.us-west-002.backblazeb2.com
        S3_KEY: 002bde636d6efa60000000001
        S3_SECRET: K002RflL669GuhXI0qdWnID+wkO9oAA
        S3_BUCKET: logicful-forms
        DYNAMO_REGION: us-east-1
        SQS_REGION: us-east-1
        SQS_ENDPOINT: https://sqs.us-east-1.amazonaws.com/033622333395/logicful_form_submission
        DYNAMO_IS_LOCAL: false
        DYNAMO_ENDPOINT: FILLED_IN_BY_AWS
        FORM_SUBMISSION_QUEUE: https://sqs.us-east-1.amazonaws.com/033622333395/logicful_form_submission
        AWS_ACCESS_KEY_ID: AKIAQPVAMC7JZKV47CF2
        AWS_SECRET_ACCESS_KEY: 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

Resources:

  CreateOptionSet:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: lambda/create-option-set/
      Handler: create-option-set
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /option-set/set
            Method: POST

  ListOptionSet:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: lambda/list-option-set/
      Handler: list-option-set
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /option-set/list
            Method: GET

  S3SetJson:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/s3-set-json/
      Handler: s3-set-json
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /s3/json/set
            Method: POST

  SetForm:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/set-form/
      Policies: AmazonDynamoDBFullAccess
      Handler: set-form
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /form/set
            Method: POST

  ListForms:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/list-forms/
      Policies: AmazonDynamoDBFullAccess
      Handler: list-forms
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /form/list
            Method: GET

  CreateContentBlock:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: lambda/set-content-block/
      Handler: set-content-block
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /content-block/set
            Method: POST

  ListContentBlock:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: lambda/list-content-block/
      Handler: list-content-block
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /content-block/list
            Method: GET

  SubmitForm:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: lambda/submit-form/
      Handler: submit-form
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /form/{id}/submit
            Method: POST

  ListFormSubmissions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/list-form-submissions/
      Policies: AmazonDynamoDBFullAccess
      Handler: list-form-submissions
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /form/{id}/submissions
            Method: GET

  FormSubmissionQueueHandler:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
        - SQSPollerPolicy:
            QueueName:
              arn:aws:sqs:us-east-1:033622333395:logicful_form_submission
      CodeUri: lambda/sqs-form-submission-handler/
      Handler: sqs-form-submission-handler
      Runtime: go1.x
      Timeout: 600
      Events:
        Sqs:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:033622333395:logicful_form_submission
            BatchSize: 1
