AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  logicful

  Sample SAM Template for logicful

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 15
    Environment:
      Variables:
        S3_ENDPOINT: s3.us-west-002.backblazeb2.com
        S3_KEY: 002bde636d6efa60000000001
        S3_SECRET: K002RflL669GuhXI0qdWnID+wkO9oAA
        S3_BUCKET: logicful-forms
        DYNAMO_REGION: us-east-1
        SQS_REGION: us-east-1
        SQS_ENDPOINT: https://sqs.us-east-1.amazonaws.com/033622333395/logicful_form_submission
        DYNAMO_IS_LOCAL: false
        DYNAMO_ENDPOINT: FILLED_IN_BY_AWS
        FORM_SUBMISSION_QUEUE: https://sqs.us-east-1.amazonaws.com/033622333395/logicful_form_submission
        FORM_SUBMISSIONS_DELETED: https://sqs.us-east-1.amazonaws.com/033622333395/logicful_form_delete_submissions,

Resources:

  Api:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: lambda/api
      Handler: api
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY

  FormSubmissionQueueHandler:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
        - SQSPollerPolicy:
            QueueName:
              logicful_form_submission
      CodeUri: lambda/sqs/sqs-form-submission-handler/
      Handler: sqs-form-submission-handler
      Runtime: go1.x
      Timeout: 600
      Events:
        Sqs:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:033622333395:logicful_form_submission
            BatchSize: 10

  FormSubmissionDeleteQueueHandler:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
        - SQSPollerPolicy:
            QueueName:
              logicful_form_delete_submissions
      CodeUri: lambda/sqs/sqs-form-submission-delete-handler/
      Handler: sqs-form-submission-delete-handler
      Runtime: go1.x
      Timeout: 600
      Events:
        Sqs:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:033622333395:logicful_form_delete_submissions
            BatchSize: 10
