service: services

app: logicful
org: logicful

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true

package:
  exclude:
    - lib/**
    - .git/**
    - dist/**
    - node_modules/**
    - '!node_modules/node-fetch/**'

provider:
  name: aws
  runtime: nodejs12.x

  environment:
    NODE_PATH: src

  iamRoleStatements:
    - Effect: Allow
      Action: 
        - logs:CreateLogGroup,
        - logs:CreateLogStream,
        - logs:PutLogEvents,
        - logs:DescribeLogStreams
      Resource: "arn:aws:logs:*:*:*"

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:TransactWriteItems
        - dynamodb:CreateTable
        - dynamodb:*
      Resource: "*"

functions:
  hello:
    handler: src/http/handlers/ValidateAddressHandler.validateAddress
    timeout: 45
    events:
      - http:
          path: field/address/validate
          method: post
          cors: true
  storeJson:
    handler: src/http/handlers/StoreJsonFileHttpHandler.storeJsonFile
    timeout: 45
    events:
      - http:
          path: file/json/store
          method: post
          cors: true

  option_set-set:
    handler: src/http/handlers/SetOptionSetHttpHandler.setOptionSet
    timeout: 45
    events:
      - http:
          path: option_sets/set
          method: post
          cors: true

  option_set-list:
    handler: src/http/handlers/GetOptionSetsHttpHandler.getOptionSets
    timeout: 45
    events:
      - http:
          path: option_sets/list
          method: get
          cors: true